config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'

  get 'user/logout', to: 'users#logout', as: :user_logout
  devise_for :users

  resources :games, only: %i[index show]
  resources :campaigns, only: %i[show]

  resource :dashboard, only: %i[show] do
    member { get :me }
  end

  resource :user, only: %i[update] do
    member { patch :avatar_update }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
# frozen_string_literal: true

class Campaign < ApplicationRecord
  belongs_to :game
  belongs_to :game_master, class_name: 'User'
end

app/models/campain.rb
# frozen_string_literal: true

class Campain < ApplicationRecord
  belongs_to :game
  belongs_to :game_master, class_name: 'User'
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  has_many :campaigns, dependent: :restrict_with_error
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :led_campaigns, class_name: 'Campaign',
                           foreign_key: 'game_master_id',
                           inverse_of: :game_master,
                           dependent: :nullify

  has_one_attached :avatar
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController: Common methods and helpers for all controllers
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def stream
    @stream ||= ComponentStream.new(controller: self)
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def show
    @campaign = Campaign.find(params[:id])
    authorize @campaign
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :skip_authorization
end

app/controllers/games_controller.rb
# frozen_string_literal: true

# GamesController
class GamesController < ApplicationController
  def index
    @games = policy_scope(Game)
  end

  def show
    @game = Game.find(params[:id])
    authorize @game

    @campaigns = policy_scope(@game.campaigns)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Serve Static Pages
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Actions on current_user
class UsersController < ApplicationController
  before_action :skip_authorization

  def logout
    sign_out current_user
    redirect_to root_path
  end

  def update
    current_user.update(user_params)

    respond_to do |format|
      format.any(:html, :json, :js) { head :no_content }
      format.turbo_stream do
        stream.add(action: :replace, id: current_user, component: PageHeader, model: current_user)
              .render
      end
    end
  end

  def avatar_update
    current_user.update(avatar: params[:user][:avatar])

    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.turbo_stream do
        stream.add(action: :replace, id: current_user, component: PageHeader, model: current_user)
              .add(action: :replace, id: 'user_icon', component: Navbar::UserMenu, user: current_user)
              .render
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/view_component_helper.rb
# frozen_string_literal: true

## For side-car components only
## <%= component :component_name %> if no ambiguity between components
## <%= component "namespace1/namespace2/component_name" %> to target a specific component
module ViewComponentHelper
  def component(name, context: nil, **args, &block)
    return component_class_from_name(name).new(**args).render_in(context, &block) if context

    render(component_class_from_name(name).new(**args), &block)
  end

  private

  def component_class_from_name(name)
    namespace = name.to_s
                    .split('/')

    component_path = if namespace.count == 1
                       component_path_from_name(namespace.first)
                     else
                       namespace
                     end

    "#{namespace_to_string(component_path)}::Component".constantize
  end

  def namespace_to_string(component_path)
    component_path.map(&:classify)
                  .join('::')
  end

  def component_path_from_name(component_name)
    Dir.glob(Rails.root.join('app', 'components', '**', component_name))
       .first
       .split('/')
       .drop_while { |item| item != 'components' }[1..]
  end
end

app/views/campaigns/_campaign.html.erb
<%= link_to campaign_path(campaign) do  %>
  <div>
    <h1><%= campaign.name %></h1>

    <h2>Maître de jeu: <%= campaign.game_master.name %></h2>
  </div>
<% end %>
  

app/views/campaigns/show.html.erb
<h1>Campaigns#show</h1>
<p>Find me in app/views/campaigns/show.html.erb</p>

app/views/dashboards/me.html.erb
<%= turbo_frame_tag "user_menu" do %>
  <ul
    class="flex flex-col items-center"
    data-navbar--user-menu--component-target="menu"
  >
    <%= component :"navbar/navitem", name: "Éditer le profil", url: dashboard_path, highlight: false do %>
      <svg aria-hidden="true" focusable="false" data-prefix="fad" data-icon="user-circle" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512" class="svg-inline--fa fa-user-circle fa-w-16 fa-9x w-8 min-w-8 m-x-6"><g class="fa-group"><path fill="currentColor" d="M248,8C111,8,0,119,0,256S111,504,248,504,496,393,496,256,385,8,248,8Zm0,96a88,88,0,1,1-88,88A88,88,0,0,1,248,104Zm0,344a191.61,191.61,0,0,1-146.5-68.2C120.3,344.4,157.1,320,200,320a24.76,24.76,0,0,1,7.1,1.1,124.67,124.67,0,0,0,81.8,0A24.76,24.76,0,0,1,296,320c42.9,0,79.7,24.4,98.5,59.8A191.61,191.61,0,0,1,248,448Z" class="text-primary"></path><path fill="currentColor" d="M248,280a88,88,0,1,0-88-88A88,88,0,0,0,248,280Zm48,40a24.76,24.76,0,0,0-7.1,1.1,124.67,124.67,0,0,1-81.8,0A24.76,24.76,0,0,0,200,320c-42.9,0-79.7,24.4-98.5,59.8,68.07,80.91,188.84,91.32,269.75,23.25A192,192,0,0,0,394.5,379.8C375.7,344.4,338.9,320,296,320Z" class="text-secondary"></path></g></svg>
    <% end %>
    <%= component :"navbar/navitem", name: "Se déconnecter", url: user_logout_path, highlight: false do %>
      <svg aria-hidden="true" focusable="false" data-prefix="fad" data-icon="sign-out" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="svg-inline--fa fa-sign-out fa-w-16 fa-9x w-8 min-w-8 m-x-6"><g class="fa-group"><path fill="currentColor" d="M180 448H96a96 96 0 0 1-96-96V160a96 96 0 0 1 96-96h84a12 12 0 0 1 12 12v40a12 12 0 0 1-12 12H96a32 32 0 0 0-32 32v192a32 32 0 0 0 32 32h84a12 12 0 0 1 12 12v40a12 12 0 0 1-12 12z" class="text-secondary"></path><path fill="currentColor" d="M353 88.3l151.9 150.6a24 24 0 0 1 0 34.1l-152 150.8a24.08 24.08 0 0 1-33.9-.1l-21.9-21.9a24.07 24.07 0 0 1 .8-34.7l77.6-71.1H184a23.94 23.94 0 0 1-24-24v-32a23.94 23.94 0 0 1 24-24h191.5l-77.6-71.1a24 24 0 0 1-.7-34.6l21.9-21.9a24 24 0 0 1 33.9-.1z" class="text-primary"></path></g></svg>
    <% end %>
  </ul>
<% end %>

app/views/dashboards/show.html.erb
<%= component :page_header, model: current_user %>

<section class="dashboard">
  <h2>Mes informations</h2>
  <%=
    form_with(model: current_user,
              class: "update_form",
              data: {
                'controller': 'auto-submit-form',
                'auto-submit-form-target': 'form'
              }) do |f|
  %>
    <%= f.label :name %>
    <%=
      f.text_field(:name,
                  'data-auto-submit-form-target': 'name',
                  'data-action': 'keyup->auto-submit-form#submit'
                  )
    %>
    <%= f.label :email %>
    <%=
      f.text_field(:email,
                  'data-auto-submit-form-target': 'email',
                  'data-action': 'keyup->auto-submit-form#submit'
                  )
    %>
  <% end %>
</section>

<section class="dashboard">
  <h2>Changer mon mot de passe</h2>
  
  <%= form_with(model: User.new, url: registration_path(:user), class: "update_form", html: { method: :put }) do |f| %>
    <%#= render "devise/shared/error_messages", resource: current_user %>

    <%= f.label :password, t('devise.passwords.edit.new_password') %>
    <%= f.password_field :password, autocomplete: "new-password" %>


    <%= f.label :password_confirmationt, t('devise.passwords.edit.confirm_new_password') %>
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>

    <%= f.label :current_password, class: "pt-6" %>
    <%= f.password_field :current_password, autocomplete: "current-password", class: "mt-6" %>

    <%= component :button, text: t('devise.registrations.edit.update'), type: :submit %>
  <% end %>
</section>

app/views/games/_game.html.erb
<li>
  <%= link_to(game.name, game_path(game)) %>
</li>

app/views/games/index.html.erb
<h1>Games#index</h1>

<ul>
  <%= render @games %>
</ul>

app/views/games/show.html.erb
<h1><%= @game.name %></h1>
Campagnes en cours :

<ul>
  <%= render @campaigns %>
</ul>

<%= link_to "Créer une nouvelle campagne", "#TODO" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compendium</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "inter-font" %>
    <%= stylesheet_link_tag "tailwind" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= stimulus_include_tags %>
    <%= javascript_include_tag "turbo", type: "module-shim" %>
    <%= yield :head %>
  </head>
  <body>
    <header>
      <%= render 'shared/navbar' %>
    </header>

    <main>
      <%= yield %>
      <%#= render 'shared/flash_notifications' %>
    </main>

    <footer>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<section class="home grid h-screen w-full grid-cols-1 grid-rows-1">
  <%= image_tag 'home/rpg_table.webp', class: 'col-start-1 row-start-1 h-full object-cover z-0'%>
  <div class="home--backdrop col-start-1 row-start-1 h-full w-full z-10"></div>

  <div class="col-start-1 row-start-1 ml-16  self-center pt-64 z-20">
    <h1 class="home--title text-left text-7xl mb-4 text-white uppercase">Compendium</h1>
    <p class="home--description text-white text-lg ml-4 w-1/2">
      Vos notes de campagnes de JDR. Toujours disponibles. Partout.
    </p>
    <div class="mt-10 ml-4">
      <%= component :button, text: 'Commencez ici !', url: games_path %>
    </div>
  </div>
</section>

app/views/shared/_flash_notifications.html.erb
<div class="fixed inset-0 px-4 py-6 pointer-events-none sm:p-6 sm:items-start sm:justify-end">
  <div class="flex flex-col items-end justify-center gap-4">
    <% flash.each do |type, data| %>
      <%= component :notification, type: type, data: data %>
    <% end %>
  </div>
</div>